
export const TokenSelection = {
  Offline: [],
  'Local RPC': [],
  'Ropsten Testnet': [
    {
      symbol: 'symb',
      name: 'Hot Symbol',
      contractAddress: '0x0a460180ec4fd3d5eb9dca8f84e8ca45b2ad9160',
      decimals: 18,
      description: 'The most distributed token ever',
      url: 'https://eth-hot-wallet.com',
    },
    {
      symbol: 'mero',
      name: 'MonetaryCoin Ero',
      contractAddress: '0xb39fc5e11281012b4d83407a457d409ba344744f',
      decimals: 18,
      description: 'The MonetaryCoin protocol integrates Nobel Prize winning economic theory with blockchain technology.',
      url: 'https://MonetaryCoin.org',
    },
    {
      symbol: 'omg',
      name: 'OmiseGo',
      contractAddress: '0xbcad569fe454e78ca90e4120d89b6b69f8db402f',
      decimals: 18,
      description: 'OmiseGO (OMG) is a public Ethereum-based financial technology for use in mainstream digital wallets',
      url: 'https://omisego.network/',
    },
    {
      symbol: 'bat',
      name: 'Basic Attention Token',
      contractAddress: '0xf3a1c162bc4a82ca5227d7c542c20dd087d2c37b',
      decimals: 18,
      description: 'The Basic Attention Token is the new token for the digital advertising industry',
      url: 'https://basicattentiontoken.org/',
    },
    {
      symbol: 'mkr',
      name: 'Maker',
      contractAddress: '0xece9fa304cc965b00afc186f5d0281a00d3dbbfd',
      decimals: 18,
      description: 'Maker is a Decentralized Autonomous Organization that creates and insures the dai stablecoin on the Ethereum blockchain',
      url: 'https://makerdao.com/',
    },
  ],
  'Main Net': [
    {
      symbol: 'mero',
      name: 'MonetaryCoin Ero',
      contractAddress: '0x227412a7d92bca453b5e2f790fc8282ca2e1a686',
      decimals: 18,
      description: 'The MonetaryCoin protocol integrates Nobel Prize winning economic theory with blockchain technology.',
      url: 'https://MonetaryCoin.org',
    },
    {
      symbol: 'eos',
      name: 'EOS',
      contractAddress: '0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0',
      decimals: 18,
      description: 'Infrastructure for Decentralized Applications',
      url: 'https://eos.io/',
    },
    {
      symbol: 'trx',
      name: 'Tron',
      contractAddress: '0xf230b790e05390fc8295f4d3f60332c93bed42e2',
      decimals: 6,
      description: 'TRON is a blockchain-based decentralized protocol that aims to construct a worldwide free content entertainment system',
      url: 'https://tronlab.com/',
    },
    {
      symbol: 'icx',
      name: 'Icon',
      contractAddress: '0xb5a5f22694352c15b00323844ad545abb2b11028',
      decimals: 18,
      description: 'Hyperconnect the World',
      url: 'https://icon.foundation/',
    },
    {
      symbol: 'qtum',
      name: 'Qtum',
      contractAddress: '0x9a642d6b3368ddc662CA244bAdf32cDA716005BC',
      decimals: 18,
      description: 'Build Decentralized Applications that Simply Work Executable on mobile devices, compatible with major existing blockchain ecosystem',
      url: 'https://qtum.org/',
    },
    {
      symbol: 'omg',
      name: 'OmiseGo',
      contractAddress: '0xd26114cd6EE289AccF82350c8d8487fedB8A0C07',
      decimals: 18,
      description: 'OmiseGO (OMG) is a public Ethereum-based financial technology for use in mainstream digital wallets',
      url: 'https://omisego.network/',
    },
    {
      symbol: 'rdn',
      name: 'Raiden',
      contractAddress: '0x255aa6df07540cb5d3d297f0d0d4d84cb52bc8e6',
      decimals: 18,
      description: 'The Raiden Network is an off-chain scaling solution',
      url: 'https://raiden.network/',
    },
    {
      symbol: 'bnb',
      name: 'Binance',
      contractAddress: '0xB8c77482e45F1F44dE1745F52C74426C631bDD52',
      decimals: 18,
      description: 'Binance will build a world-class crypto exchange, powering the future of crypto finance',
      url: 'https://www.binance.com/',
    },
    {
      symbol: 'snt',
      name: 'Status Network',
      contractAddress: '0x744d70fdbe2ba4cf95131626614a1763df805b9e',
      decimals: 18,
      description: 'Status is an open source messaging platform and mobile browser to interact with decentralized applications that run on the Ethereum Network',
      url: 'https://status.im/',
    },
    {
      symbol: 'mkr',
      name: 'Maker',
      contractAddress: '0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2',
      decimals: 18,
      description: 'Maker is a Decentralized Autonomous Organization that creates and insures the dai stablecoin on the Ethereum blockchain',
      url: 'https://makerdao.com/',
    },
    {
      symbol: 'zrx',
      name: '0xProject',
      contractAddress: '0xe41d2489571d322189246dafa5ebde1f4699f498',
      decimals: 18,
      description: 'The Protocol for Trading Tokens',
      url: 'https://0xproject.com/',
    },
    {
      symbol: 'rep',
      name: 'Augur',
      contractAddress: '0xe94327d07fc17907b4db788e5adf2ed424addff6',
      decimals: 18,
      description: 'Augur combines the magic of prediction markets with the power of a decentralized network to create a stunningly accurate forecasting tool',
      url: 'https://www.augur.net/',
    },
    {
      symbol: 'salt',
      name: 'Salt',
      contractAddress: '0x4156D3342D5c385a87D264F90653733592000581',
      decimals: 8,
      description: 'SALT lets you leverage your blockchain assets to secure cash loans. We make it easy to get money without having to sell your favorite investment',
      url: 'https://saltlending.com/',
    },
    {
      symbol: 'bat',
      name: 'Basic Attention Token',
      contractAddress: '0x0d8775f648430679a709e98d2b0cb6250d2887ef',
      decimals: 18,
      description: 'The Basic Attention Token is the new token for the digital advertising industry',
      url: 'https://basicattentiontoken.org/',
    },
    {
      symbol: 'fun',
      name: 'FunFair',
      contractAddress: '0x419d0d8bdd9af5e606ae2232ed285aff190e711b',
      decimals: 8,
      description: 'FunFair is a decentralised gaming platform powered by Ethereum smart contracts',
      url: 'https://www.funfair.io/',
    },
    {
      symbol: 'qash',
      name: 'Qash',
      contractAddress: '0x618e75ac90b12c6049ba3b27f5d5f8651b0037f6',
      decimals: 6,
      description: 'We envision QASH to be the preferred payment token for financial services, like the Bitcoin for financial services',
      url: 'https://liquid.plus/',
    },
    {
      symbol: 'gnt',
      name: 'GOLEM',
      contractAddress: '0xa74476443119A942dE498590Fe1f2454d7D4aC0d',
      decimals: 18,
      description: 'Golem is going to create the first decentralized global market for computing power',
      url: 'https://golem.network/',
    },
    {
      symbol: 'knc',
      name: 'Kyber Network Crystal',
      contractAddress: '0xdd974d5c2e2928dea5f71b9825b8b646686bd200',
      decimals: 18,
      description: 'KyberNetwork is a new system which allows the exchange and conversion of digital assets',
      url: 'https://kyber.network/',
    },
    {
      symbol: 'ethos',
      name: 'ETHOS',
      contractAddress: '0x5af2be193a6abca9c8817001f45744777db30756',
      decimals: 18,
      description: 'People-powered cryptocurrency services for the blockchain',
      url: 'https://www.ethos.io/',
    },
    {
      symbol: 'req',
      name: 'Request',
      contractAddress: '0x8f8221afbb33998d8584a2b05749ba73c37a938a',
      decimals: 18,
      description: 'A decentralized network built on top of Ethereum, which allows anyone, anywhere to request a payment',
      url: 'https://request.network/',
    },
    {
      symbol: 'dgd',
      name: 'Digix Global',
      contractAddress: '0xe0b7927c4af23765cb51314a0e0521a9645f0e2a',
      decimals: 9,
      description: 'Every asset represents a unique bullion bar sitting in designated securitised custodial vaults',
      url: 'https://digix.io/',
    },
    {
      symbol: 'qsp',
      name: 'Quantstamp',
      contractAddress: '0x99ea4db9ee77acd40b119bd1dc4e33e1c070b80d',
      decimals: 18,
      description: 'Quantstamp – the Protocol for Securing Smart Contracts',
      url: 'https://quantstamp.com/',
    },
    {
      symbol: 'bnt',
      name: 'Bancor Network',
      contractAddress: '0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c',
      decimals: 18,
      description: 'Bancor Protocol is a standard for a new generation of cryptocurrencies called Smart Tokens',
      url: 'https://bancor.network/',
    },
  ],
};

export default TokenSelection;
/*
{
  symbol: '',
  name: '',
  contractAddress: '',
  decimals: 18,
  description: '',
},
*/
